package topgun.cmdline;
public enum AggregateView {
    PACKAGE_CLASSNAME_METHOD_LINE_VIEW,
    PACKAGE_CLASSNAME_METHOD_VIEW,
    PACKAGE_CLASSNAME_VIEW,
    PACKAGE_VIEW,
    PACKAGE_SOURCE_METHOD_VIEW,//Not done
    PACKAGE_SOURCE_LINE_VIEW
}
